service: horses-mouth-backend

frameworkVersion: "2"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${env:APP_ENV} # Default stage to be used. Default is "dev"
  region: ap-south-1
  timeout: 20
  lambdaHashingVersion: 20201221
  apiName: ${self:service}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObjectAcl
            - s3:GetObject
            - s3:GetObjectAcl
            - s3:DeleteObject
          Resource:
            - "*"

resources:
  Resources:
    S3Bucket: ${file(resources/s3Bucket.yaml):S3Bucket}
    S3BucketPolicy: ${file(resources/s3Bucket.yaml):S3BucketPolicy}

functions:
  api:
    handler: src/lambda.handler
    timeout: 10
    reservedConcurrency: 5
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-mongodb-local
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-s3-remover
  - serverless-dotenv-plugin

package:
  include:
    - api-docs.yaml
    - service-account.json

custom:
  remover:
    buckets:
      - ${env:UPLOAD_BUCKET}
  S3Bucket:
    name: ${env:UPLOAD_BUCKET}
  mongodb:
    stages: # If you only want to use MongoDB Local in particular stages, declare them here
      - DEV
    seed:
      auto: true
      dataPath: ./seed
